<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    
    $orderAdminDate = $block->formatDate(
        $block->getOrderAdminDate($_order->getCreatedAt()),
        \IntlDateFormatter::MEDIUM,
        true
    );
    
    $orderStoreDate = $block->formatDate(
        $_order->getCreatedAt(),
        \IntlDateFormatter::MEDIUM,
        true,
        $block->getTimezoneForStore($_order->getStore())
    );
    $customerEmail  = $_order->getCustomerEmail();
    $account_number = "";
    if ($customerEmail) {
        $customerRepository  = $objectManager->create('Magento\Customer\Api\CustomerRepositoryInterface');
        $customer  = $objectManager->create('Magento\Customer\Model\Customer');
        $customer->setWebsiteId(1);
        $customerInfo = $customer->loadByEmail($customerEmail);
        if ($customerInfo->getId()) {
            $customerId = $customerInfo->getId();
            $cData = $customerRepository->getById($customerId);
            $accInfo = (array)$cData->getCustomAttribute('account_number');
            foreach ($accInfo as $numberInfo) {
                $account_number =  $numberInfo['value'];
            }
        }
    }
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order & Account Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */?>
            <?php if ($_order->getEmailSent()):
                $_email = __('The order confirmation email was sent');
            else:
                $_email = __('The order confirmation email is not sent');
            endif; ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()): ?>
                        <?php /* @escapeNotVerified */ echo __('Order # %1', $_order->getRealOrderId()) ?> (<span><?php /* @escapeNotVerified */ echo $_email ?></span>)
                    <?php else: ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getId()) ?>"><?php /* @escapeNotVerified */ echo __('Order # %1', $_order->getRealOrderId()) ?></a>
                        <span>(<?php /* @escapeNotVerified */ echo $_email ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Order Date') ?></th>
                    <td><?php /* @escapeNotVerified */ echo $orderAdminDate ?></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate):?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __(
                                'Order Date (%1)',
                                $block->getTimezoneForStore($_order->getStore())
                            ) ?></th>
                        <td><?php /* @escapeNotVerified */ echo $orderStoreDate ?></td>
                    </tr>
                <?php endif;?>
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Order Status') ?></th>
                    <td><span id="order_status"><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></span></td>
                </tr>
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Order Source') ?></th>
                    <td><span id="order_source"><?php /* @escapeNotVerified */ echo $_order->getSource() ?></span></td>
                </tr>
                
                <?php if($merchantSource = $_order->getMerchantSource()):?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Merchant Source') ?></th>
                        <td><span id="merchant_source"><?php /* @escapeNotVerified */ echo $merchantSource ?></span></td>
                    </tr>
                <?php endif?>
                
                <?php if($_order->getData('admin_id')): ?>
                    <?php $_user = $objectManager->create('Magento\User\Model\UserFactory')->create()->load($_order->getData('admin_id')); ?>
                    <?php if($_user->getId()): ?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo __('Admin Account') ?></th>
                            <td>
                                <a target="_blank" href="<?php /* @escapeNotVerified */ echo $block->getUrl('adminhtml/user/edit', ['user_id' => $_order->getData('admin_id')]) ?>">
                                    <?php /* @escapeNotVerified */ echo $_user->getFirstName() . ' ' . $_user->getLastName() ?> (<?php echo $_user->getUserName(); ?>)
                                </a>
                            </td>
                        </tr>
                    <?php endif ?>
                <?php endif ?>

                <?php if ($block->isSingleStoreMode() == false):?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Purchased From') ?></th>
                        <td><?php /* @escapeNotVerified */ echo $block->getOrderStoreName() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationChildId()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Link to the New Order') ?></th>
                        <td><a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getRelationChildId()) ?>">
                                <?php /* @escapeNotVerified */ echo $_order->getRelationChildRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationParentId()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Link to the Previous Order') ?></th>
                        <td><a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getRelationParentId()) ?>">
                                <?php /* @escapeNotVerified */ echo $_order->getRelationParentRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRemoteIp() && $block->shouldDisplayCustomerIp()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Placed from IP') ?></th>
                        <td><?php /* @escapeNotVerified */ echo $_order->getRemoteIp(); echo($_order->getXForwardedFor()) ? ' (' . $block->escapeHtml($_order->getXForwardedFor()) . ')' : ''; ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('%1 / %2 rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></th>
                        <td><?php /* @escapeNotVerified */ echo $_order->getBaseToGlobalRate() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('%1 / %2 rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></th>
                        <th><?php /* @escapeNotVerified */ echo $_order->getBaseToOrderRate() ?></th>
                    </tr>
                <?php endif; ?>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Account Information') ?></span>
                <div class="actions"><?php /* @escapeNotVerified */ echo $block->getAccountEditLink()?></div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Customer Name') ?></th>
                        <td>
                            <?php if ($_customerUrl = $block->getCustomerViewUrl()) : ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_customerUrl ?>" target="_blank">
                                    <span><?php echo $block->escapeHtml($_order->getCustomerName()) ?></span>
                                </a>
                            <?php else: ?>
                                <?php echo $block->escapeHtml($_order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Email') ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($_order->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($_order->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($_groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo __('Customer Group') ?></th>
                            <td><?php /* @escapeNotVerified */ echo $_groupName ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($account_number) : ?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo __('Account Number') ?></th>
                            <td><?php /* @escapeNotVerified */ echo $account_number ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data):?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo $data['label'] ?></th>
                            <td><?php /* @escapeNotVerified */ echo $data['value'] ?></td>
                        </tr>
                    <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Address Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span>
                <div class="actions"><?php /* @escapeNotVerified */ echo $block->getAddressEditLink($_order->getBillingAddress()); ?></div>
            </div>
            <address class="admin__page-section-item-content"><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getBillingAddress()); ?></address>
        </div>
        <?php if (!$block->getOrder()->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span>
                    <div class="actions"><?php /* @escapeNotVerified */ echo $block->getAddressEditLink($_order->getShippingAddress()); ?></div>
                </div>
                <address class="admin__page-section-item-content"><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
            </div>
        <?php endif; ?>
    </div>
</section>